export const DELETE_ARTICLE = 'DELETE_ARTICLE',
             INCREMENT = 'INCREMENT',
             CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE',
             CHANGE_SELECTION = 'CHANGE_SELECTION',
             ADD_COMMENT = 'ADD_COMMENT'