export const DELETE_ARTICLE = 'DELETE_ARTICLE',
             INCREMENT = 'INCREMENT',
             SELECT_ARTICLE = 'SELECT_ARTICLE',
             CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE',
             CHANGE_SELECTION = 'CHANGE_SELECTION'